// GENERATED by scripts/gen-kit-css-variables.mjs — do not edit by hand. Re-run it after
// changing tokens.css or upgrading Tailwind; src/__tests__/token-vars-declared.test.ts
// fails while this is stale.

/** Every custom property tokens.css declares, `@theme inline` names and `--app-nav-h`
 *  left out (100 names). */
export const KIT_NAMES =
  "--bg-active --bg-hover --bg-inverse --bg-page --bg-surface --bg-surface-2 --border " +
  "--border-strong --brand --brand-bg --brand-bg-hover --brand-contrast --brand-hover --brand-muted " +
  "--breakpoint-3xl --chart-1 --chart-2 --chart-3 --chart-4 --chart-5 --chart-6 --chart-7 --chart-8 " +
  "--chart-9 --danger --danger-bg --danger-border --danger-border-strong --danger-contrast " +
  "--danger-hover --flyout-from --focus-ring-width --hue-blue --hue-blue-bg --hue-blue-border " +
  "--hue-blue-contrast --hue-indigo --hue-indigo-bg --hue-indigo-border --hue-indigo-contrast " +
  "--hue-orange --hue-orange-bg --hue-orange-border --hue-orange-contrast --hue-purple " +
  "--hue-purple-bg --hue-purple-border --hue-purple-contrast --hue-teal --hue-teal-bg " +
  "--hue-teal-border --hue-teal-contrast --info --info-bg --info-border --info-contrast --media-ink " +
  "--media-scrim --media-scrim-hover --money-expense --money-expense-contrast --money-income " +
  "--money-income-contrast --money-net --money-net-contrast --money-neutral " +
  "--money-neutral-contrast --neutral --neutral-contrast --status-edited --status-error " +
  "--status-pending --status-synced --success --success-bg --success-border --success-contrast " +
  "--text-caption --text-inverse --text-micro --text-muted --text-placeholder --text-primary " +
  "--text-secondary --toast-action-bg --toast-action-fg --toast-danger-bg --toast-danger-border " +
  "--toast-info-bg --toast-info-border --toast-success-bg --toast-success-border --toast-warning-bg " +
  "--toast-warning-border --warning --warning-bg --warning-border --warning-border-strong " +
  "--warning-contrast --z-toast";

/** The theme variables of Tailwind 4.3.3's `theme.css` (413 names). */
export const TAILWIND_THEME_NAMES =
  "--animate-bounce --animate-ping --animate-pulse --animate-spin --aspect-video --blur-2xl " +
  "--blur-3xl --blur-lg --blur-md --blur-sm --blur-xl --blur-xs --breakpoint-2xl --breakpoint-lg " +
  "--breakpoint-md --breakpoint-sm --breakpoint-xl --color-amber-100 --color-amber-200 " +
  "--color-amber-300 --color-amber-400 --color-amber-50 --color-amber-500 --color-amber-600 " +
  "--color-amber-700 --color-amber-800 --color-amber-900 --color-amber-950 --color-black " +
  "--color-blue-100 --color-blue-200 --color-blue-300 --color-blue-400 --color-blue-50 " +
  "--color-blue-500 --color-blue-600 --color-blue-700 --color-blue-800 --color-blue-900 " +
  "--color-blue-950 --color-cyan-100 --color-cyan-200 --color-cyan-300 --color-cyan-400 " +
  "--color-cyan-50 --color-cyan-500 --color-cyan-600 --color-cyan-700 --color-cyan-800 " +
  "--color-cyan-900 --color-cyan-950 --color-emerald-100 --color-emerald-200 --color-emerald-300 " +
  "--color-emerald-400 --color-emerald-50 --color-emerald-500 --color-emerald-600 " +
  "--color-emerald-700 --color-emerald-800 --color-emerald-900 --color-emerald-950 " +
  "--color-fuchsia-100 --color-fuchsia-200 --color-fuchsia-300 --color-fuchsia-400 " +
  "--color-fuchsia-50 --color-fuchsia-500 --color-fuchsia-600 --color-fuchsia-700 " +
  "--color-fuchsia-800 --color-fuchsia-900 --color-fuchsia-950 --color-gray-100 --color-gray-200 " +
  "--color-gray-300 --color-gray-400 --color-gray-50 --color-gray-500 --color-gray-600 " +
  "--color-gray-700 --color-gray-800 --color-gray-900 --color-gray-950 --color-green-100 " +
  "--color-green-200 --color-green-300 --color-green-400 --color-green-50 --color-green-500 " +
  "--color-green-600 --color-green-700 --color-green-800 --color-green-900 --color-green-950 " +
  "--color-indigo-100 --color-indigo-200 --color-indigo-300 --color-indigo-400 --color-indigo-50 " +
  "--color-indigo-500 --color-indigo-600 --color-indigo-700 --color-indigo-800 --color-indigo-900 " +
  "--color-indigo-950 --color-lime-100 --color-lime-200 --color-lime-300 --color-lime-400 " +
  "--color-lime-50 --color-lime-500 --color-lime-600 --color-lime-700 --color-lime-800 " +
  "--color-lime-900 --color-lime-950 --color-mauve-100 --color-mauve-200 --color-mauve-300 " +
  "--color-mauve-400 --color-mauve-50 --color-mauve-500 --color-mauve-600 --color-mauve-700 " +
  "--color-mauve-800 --color-mauve-900 --color-mauve-950 --color-mist-100 --color-mist-200 " +
  "--color-mist-300 --color-mist-400 --color-mist-50 --color-mist-500 --color-mist-600 " +
  "--color-mist-700 --color-mist-800 --color-mist-900 --color-mist-950 --color-neutral-100 " +
  "--color-neutral-200 --color-neutral-300 --color-neutral-400 --color-neutral-50 " +
  "--color-neutral-500 --color-neutral-600 --color-neutral-700 --color-neutral-800 " +
  "--color-neutral-900 --color-neutral-950 --color-olive-100 --color-olive-200 --color-olive-300 " +
  "--color-olive-400 --color-olive-50 --color-olive-500 --color-olive-600 --color-olive-700 " +
  "--color-olive-800 --color-olive-900 --color-olive-950 --color-orange-100 --color-orange-200 " +
  "--color-orange-300 --color-orange-400 --color-orange-50 --color-orange-500 --color-orange-600 " +
  "--color-orange-700 --color-orange-800 --color-orange-900 --color-orange-950 --color-pink-100 " +
  "--color-pink-200 --color-pink-300 --color-pink-400 --color-pink-50 --color-pink-500 " +
  "--color-pink-600 --color-pink-700 --color-pink-800 --color-pink-900 --color-pink-950 " +
  "--color-purple-100 --color-purple-200 --color-purple-300 --color-purple-400 --color-purple-50 " +
  "--color-purple-500 --color-purple-600 --color-purple-700 --color-purple-800 --color-purple-900 " +
  "--color-purple-950 --color-red-100 --color-red-200 --color-red-300 --color-red-400 " +
  "--color-red-50 --color-red-500 --color-red-600 --color-red-700 --color-red-800 --color-red-900 " +
  "--color-red-950 --color-rose-100 --color-rose-200 --color-rose-300 --color-rose-400 " +
  "--color-rose-50 --color-rose-500 --color-rose-600 --color-rose-700 --color-rose-800 " +
  "--color-rose-900 --color-rose-950 --color-sky-100 --color-sky-200 --color-sky-300 " +
  "--color-sky-400 --color-sky-50 --color-sky-500 --color-sky-600 --color-sky-700 --color-sky-800 " +
  "--color-sky-900 --color-sky-950 --color-slate-100 --color-slate-200 --color-slate-300 " +
  "--color-slate-400 --color-slate-50 --color-slate-500 --color-slate-600 --color-slate-700 " +
  "--color-slate-800 --color-slate-900 --color-slate-950 --color-stone-100 --color-stone-200 " +
  "--color-stone-300 --color-stone-400 --color-stone-50 --color-stone-500 --color-stone-600 " +
  "--color-stone-700 --color-stone-800 --color-stone-900 --color-stone-950 --color-taupe-100 " +
  "--color-taupe-200 --color-taupe-300 --color-taupe-400 --color-taupe-50 --color-taupe-500 " +
  "--color-taupe-600 --color-taupe-700 --color-taupe-800 --color-taupe-900 --color-taupe-950 " +
  "--color-teal-100 --color-teal-200 --color-teal-300 --color-teal-400 --color-teal-50 " +
  "--color-teal-500 --color-teal-600 --color-teal-700 --color-teal-800 --color-teal-900 " +
  "--color-teal-950 --color-violet-100 --color-violet-200 --color-violet-300 --color-violet-400 " +
  "--color-violet-50 --color-violet-500 --color-violet-600 --color-violet-700 --color-violet-800 " +
  "--color-violet-900 --color-violet-950 --color-white --color-yellow-100 --color-yellow-200 " +
  "--color-yellow-300 --color-yellow-400 --color-yellow-50 --color-yellow-500 --color-yellow-600 " +
  "--color-yellow-700 --color-yellow-800 --color-yellow-900 --color-yellow-950 --color-zinc-100 " +
  "--color-zinc-200 --color-zinc-300 --color-zinc-400 --color-zinc-50 --color-zinc-500 " +
  "--color-zinc-600 --color-zinc-700 --color-zinc-800 --color-zinc-900 --color-zinc-950 " +
  "--container-2xl --container-2xs --container-3xl --container-3xs --container-4xl --container-5xl " +
  "--container-6xl --container-7xl --container-lg --container-md --container-sm --container-xl " +
  "--container-xs --default-font-family --default-font-feature-settings " +
  "--default-font-variation-settings --default-mono-font-family " +
  "--default-mono-font-feature-settings --default-mono-font-variation-settings " +
  "--default-transition-duration --default-transition-timing-function --drop-shadow-2xl " +
  "--drop-shadow-lg --drop-shadow-md --drop-shadow-sm --drop-shadow-xl --drop-shadow-xs --ease-in " +
  "--ease-in-out --ease-out --font-mono --font-sans --font-serif --font-weight-black " +
  "--font-weight-bold --font-weight-extrabold --font-weight-extralight --font-weight-light " +
  "--font-weight-medium --font-weight-normal --font-weight-semibold --font-weight-thin " +
  "--inset-shadow-2xs --inset-shadow-sm --inset-shadow-xs --leading-loose --leading-normal " +
  "--leading-relaxed --leading-snug --leading-tight --perspective-distant --perspective-dramatic " +
  "--perspective-midrange --perspective-near --perspective-normal --radius-2xl --radius-3xl " +
  "--radius-4xl --radius-lg --radius-md --radius-sm --radius-xl --radius-xs --shadow-2xl " +
  "--shadow-2xs --shadow-lg --shadow-md --shadow-sm --shadow-xl --shadow-xs --spacing --text-2xl " +
  "--text-2xl--line-height --text-3xl --text-3xl--line-height --text-4xl --text-4xl--line-height " +
  "--text-5xl --text-5xl--line-height --text-6xl --text-6xl--line-height --text-7xl " +
  "--text-7xl--line-height --text-8xl --text-8xl--line-height --text-9xl --text-9xl--line-height " +
  "--text-base --text-base--line-height --text-lg --text-lg--line-height --text-shadow-2xs " +
  "--text-shadow-lg --text-shadow-md --text-shadow-sm --text-shadow-xs --text-sm " +
  "--text-sm--line-height --text-xl --text-xl--line-height --text-xs --text-xs--line-height " +
  "--tracking-normal --tracking-tight --tracking-tighter --tracking-wide --tracking-wider " +
  "--tracking-widest";
